### ISSUE TITLE
I can't run the plugin on WP 5.4.1

### ISSUE THREAD

**Issue by rasskalex** [bueltge/multisite-global-media#114]
I can't run the plugin on WP 5.4.1. Does it work on this version? Downloaded 0.1.1 zip and release versions (without composer).

There was an error in the zip version "No suitable autoloader found. Multisite Global Media cannot be loaded correctly".

There were no errors in the release version but Global Media Fodder didn't appear either.

**Comment by widoz** [comment]
Hi @rasskalex this the repository of the plugin development, when you clone the repo there are some steps you have to go through too in order to make it work. You can get a functional version by following these steps https://github.com/bueltge/multisite-global-media#installation both from source code or from .zip

**Comment by rasskalex** [comment]
Hi, @widoz sorry my mistake. I tried to find Global media in the site customize (it's missing there). In pages and others everything works, thank you.

**Comment by widoz** [comment]
Hi @rasskalex there's an issue about adding Global Media to the Customizer, if you want have a look at https://github.com/bueltge/multisite-global-media/issues/90
