### ISSUE TITLE
Doesn't work wordpress feed http://domain.com/feed/ when 'Multisite Global Media' is enabled.

### ISSUE THREAD

**Issue by JeyFisher** [bueltge/multisite-global-media#74]
Doesn't work ./feed page and error log shows next error:
PHP Parse error: syntax error, unexpected ':', expecting '{' in /wp-content/plugins/multisite-global-media/multisite-global-media.php on line 50

**Comment by widoz** [comment]
Hi @JeyFisher, which version of php are you running? Are you sure you have the latest version of the plugin?

**Comment by JeyFisher** [comment]
Hi @widoz. Thank you for your response. 
Yes, I use PHP 7.2
I used first version of the plugin. When I upgrade the plugin to dev-2 version featured images, where I used the plugin was missed. So I returned it to first.

**Comment by widoz** [comment]
@JeyFisher Really strange, at line 50 the code is `function autoload(): bool` means `syntax error, unexpected ':', expecting '{'` sounds like php doesn't expect the return type hint but the function body block, that's why I'm asking the php version. Is this the line right? https://github.com/bueltge/multisite-global-media/blob/master/multisite-global-media.php#L50

It happens only into `feed` page? Which kind of page is it?
